apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
    namespace: ${NAME}
  spec:
    ports:
    - name: 5353-5353
      port: 5353
      protocol: TCP
      targetPort: 5353
    selector:
      app: ${NAME}
    type: ClusterIP
- apiVersion: v1
  kind: Pod
  metadata:
    name: ${NAME}
    namespace: ${NAME}
    labels:
      app: ${NAME}
  spec:
    containers:
    - args:
      - -conf
      - /etc/coredns/Corefile
      command:
      - coredns
      image: ${IMAGE}
      name: dns
      ports:
      - containerPort: 5353
        name: dns
        protocol: UDP
      - containerPort: 5353
        name: dns-tcp
        protocol: TCP
      resources:
        requests:
          cpu: 50m
          memory: 70Mi
      volumeMounts:
      - mountPath: /etc/coredns
        name: config-volume
        readOnly: true
    dnsPolicy: Default
    volumes:
    - configMap:
        defaultMode: 420
        items:
        - key: Corefile
          path: Corefile
        - key: server.key
          path: server.key
        - key: server-cert.pem
          path: server-cert.pem
        name: ${NAME}
      name: config-volume
- apiVersion: v1
  kind: Pod
  metadata:
    name: openssl-client
  spec:
    volumes:
    - configMap:
        defaultMode: 420
        items:
        - key: ca-cert.pem
          path: ca-cert.pem
        name: ${NAME}
      name: config-volume
    containers:
    - name: openssl
      image: quay.io/cscribne/openssl-client:latest
      args:
      - sleep
      - "1000000"
      volumeMounts:
      - mountPath: /tmp
        name: config-volume
        readOnly: true
parameters:
- name: NAME
- name: IMAGE
- name: CLI
